### ISSUE TITLE
Update ref-arch BOMs with title and description

### ISSUE THREAD

**Issue by seansund** [cloud-native-toolkit/iascable#118]
- [ ] 160
- [ ] 165
- [ ] 170

**Comment by seansund** [comment]
I'm inclined not to make this change because of #114. We are planning to delete the files in `ref-arch/` because they are duplicates of the content in the automation-solutions. @NoeSamaille Can you make sure these changes are applied to these BOMS there?

**Comment by NoeSamaille** [comment]
@seansund sure it should be there in automation-solutions I'll double check

**Comment by NoeSamaille** [comment]
done
