### ISSUE TITLE
Install script fails to install the binary

### ISSUE THREAD

**Issue by rich-ehrhardt** [cloud-native-toolkit/iascable#124]
The install script fails to install the iascable binary into /usr/local/bin. No error is reported, however, the binary is not installed into the directory. 

Manually downloading the binary and attempting to copy gives a permission denied error. Using sudo to copy the binary does work.  /usr/local/bin is owned by root by default.

OS: MacOS 12.3

**Comment by rich-ehrhardt** [comment]
Default permissions with MacOS is for root user ownership of /usr/local/bin.

Have modified install script to download to a temp directory then sudo to final destination if Darwin (MacOS).

However, perhaps we should create a brew tap instead for Mac?

**Comment by rich-ehrhardt** [comment]
Created a homebrew installation version https://github.com/cloud-native-toolkit/homebrew-iascable which works without needing a sudo.

**Comment by rich-ehrhardt** [comment]
brew ruby script installing iascable node script not binary. Reopening.

**Comment by daniel-butler-irl** [comment]
This still seems to be an issue, is there anyone to look at it?
