### ISSUE TITLE
json encoding issue when generating software boms

### ISSUE THREAD

**Issue by triceam** [cloud-native-toolkit/iascable#142]
I'm seeing another json encoding issue when generating 160/165 software boms.   These boms reference the cluster module, and when the vars for the cluster module are generated, the default is an improperly encoded json array:

```
variable "cluster_vpc_subnets" {
  type = string
  description = "List of subnets with labels"
  default = "\"[]\""
}
```

I'm using `iascable 2.11.4` and generating the boms here:
- https://github.com/cloud-native-toolkit/automation-solutions/blob/main/boms/infrastructure/ibmcloud/openshift-fs/160-ibm-fs-openshift-dev-tools.yaml
- https://github.com/cloud-native-toolkit/automation-solutions/blob/main/boms/infrastructure/ibmcloud/openshift-fs/165-ibm-fs-openshift-workload.yaml

**Comment by seansund** [comment]
This is fixed in `2.11.5`
