### ISSUE TITLE
Error: local-exec provisioner error

### ISSUE THREAD

**Issue by thomassuedbroecker** [cloud-native-toolkit/iascable#162]
* Error:

After the execution of `terraform apply -auto-approve` I got following error.

```sh
│   with module.gitops_repo.null_resource.initialize_gitops,
│   on .terraform/modules/gitops_repo/main.tf line 91, in resource "null_resource" "initialize_gitops":
│   91:   provisioner "local-exec" {
│ 
│ Error running command
│ '.terraform/modules/gitops_repo/scripts/initialize-gitops.sh
│ 'github.com/thomassuedbroecker/iascable-vpc-openshift-argocd-gitops.git'
│ 'openshift-gitops' 'tsued-gitops-sample'': exit status 126. Output: Cloning
│ into
│ '/Users/thomassuedbroecker/Downloads/dev/iascable-vpc-openshift-argocd/example/output/my-ibm-vpc-roks-argocd/terraform/.tmp/gitops-repo/.tmpgitops'...
│ .terraform/modules/gitops_repo/scripts/initialize-gitops.sh: line 57:
│ /Users/thomassuedbroecker/Downloads/dev/iascable-vpc-openshift-argocd/example/output/my-ibm-vpc-roks-argocd/terraform/bin2/yq4:
│ cannot execute binary file
```

* Objective

I want to create a VPC, a Red Hat OpenShift and an Initial GitOps environment pointing to a private github repository.

* Situation

I verified existing boms from the [catalog](https://modules.cloudnativetoolkit.dev/#/bom-catalog) and from the automation [examples](https://github.com/cloud-native-toolkit/automation-solutions). 
Then I created my [own one](https://github.com/thomassuedbroecker/iascable-vpc-openshift-argocd/blob/main/example/my-vpc-roks-argocd-bom.yaml)

I noticed that it wasn't possible to change the variables in a bom, so I changed the variables in `variables.tf` file. Here is the [variables file](https://github.com/thomassuedbroecker/iascable-vpc-openshift-argocd/blob/main/example/output/my-ibm-vpc-roks-argocd/terraform/variables.tf). My [github project ](https://github.com/thomassuedbroecker/iascable-vpc-openshift-argocd)

* Result

   * The vpc was created successfully
   * The cluster was created successfully
   * The operators for gitops (ArgoCD and Pipelines) were successfully installed
   * The private github project wasn't configured as a repository for argoCD

**Comment by triceam** [comment]
Closing.  Not an issue with iascable.   Did you execute in the `cli-tools` container?    The automation can be executed from a local terminal, but is expected to be executed from within the [`cli-tools` ](https://github.com/cloud-native-toolkit/image-cli-tools) container, which has all dependencies already configured.
