### ISSUE TITLE
iascable fails processing ibmcloud example infrastructure bom

### ISSUE THREAD

**Issue by timroster** [cloud-native-toolkit/iascable#180]
New dependency problem being reported when running `iascable` on IBM cloud boms that recently worked:

```
iascable build -i 105-ibm-vpc-openshift.yaml 
Loading catalog from url: https://modules.cloudnativetoolkit.dev/index.yaml
Name: 105-ibm-vpc-openshift

Error: Dependent module not found: module=ibm-logdna-bind, dependency=logdna, refs=[{"source":"github.com/cloud-native-toolkit/terraform-ibm-log-analysis","version":">= 3.0.0"}]
```

@mjperrins

**Comment by timroster** [comment]
Could this be a git redirect issue? Catalog has the following for the ibm-log-analysis-bind module:

```
- source: github.com/cloud-native-toolkit/terraform-ibm-log-analysis
```

But this is now `github.com/terraform-ibm-modules/terraform-ibm-toolkit-log-analysis`

**Comment by timroster** [comment]
or maybe not redirect... just a matter of conflict in the catalog.

**Comment by timroster** [comment]
This error will happen if using `iascable` versions earlier than `2.15.0`

**Comment by balasgit** [comment]
@timroster - we are migrating the modules to new repo which you tested the log-analysis. Hence you noticed the dependency issues
