### ISSUE TITLE
The generated terraform folder should not be set to rwx for everyone

### ISSUE THREAD

**Issue by seansund** [cloud-native-toolkit/iascable#196]

**Comment by timroster** [comment]
I was investigating further the source of lax permissions in `/workspaces/current` - I believe this actually has to do with a default alpine container image which is weak which the `cli-tools` image inherits.

```
podman run -it docker.io/alpine:3.16.2 sh -c umask
0022
```

**Comment by timroster** [comment]
For the current Docker CE on Ubuntu  `20.10.18, build b40c2f6` - the bind mount of the host filesystem is not mapped to the UID of the container process. This is different from Docker Desktop which on MacOS is setting the owner of the bind mount to the UID of the container process.

In this case, not having the output automation be at least r-X for other would break the `setup-workspace.sh` execution flow. Keeping `rwX` may allow "in filesystem" terraform runs to also work.

@seansund I think we should close this issue given that we are not going to be setting a specific container process userid matching the bind mount filesystem (e.g. host) userid. There are going to be cases for bind mounts of host filesystems where the group permissions on the root group won't be met.
