### ISSUE TITLE
Creating namespace: sealed-secrets

### ISSUE THREAD

**Issue by nheidloff** [cloud-native-toolkit/iascable#234]
This happens from time to time.

https://github.ibm.com/isv-assets/watson-boms

I deleted my previous cluster half an hour earlier. Might this be related?

module.argocd-bootstrap.module.openshift_cicd.module.gitops.null_resource.argocd_operator_helm (local-exec): Error: query: failed to query with labels: secrets is forbidden: User "IAM#xxx@de.ibm.com" cannot list resource "secrets" in API group "" in the namespace "openshift-operators"
╷
│ Warning: Attribute Deprecated
│ 
│   with module.argocd-bootstrap.module.bootstrap.random_string.suffix,
│   on .terraform/modules/argocd-bootstrap.bootstrap/main.tf line 12, in resource "random_string" "suffix":
│   12:   number  = true
│ 
│ **NOTE**: This is deprecated, use `numeric` instead.
│ 
│ (and 4 more similar warnings elsewhere)
╵
╷
│ Error: local-exec provisioner error
│ 
│   with module.argocd-bootstrap.module.openshift_cicd.module.gitops.null_resource.argocd_operator_helm,
│   on .terraform/modules/argocd-bootstrap.openshift_cicd.gitops/main.tf line 79, in resource "null_resource" "argocd_operator_helm":
│   79:   provisioner "local-exec" {
│ 
│ Error running command '.terraform/modules/argocd-bootstrap.openshift_cicd.gitops/scripts/deploy-helm.sh openshift-operators argocd
│ .terraform/modules/argocd-bootstrap.openshift_cicd.gitops/charts/argocd': exit status 1. Output: WARNING: Kubernetes configuration file is group-readable.
│ This is insecure. Location:
│ /terraform/cluster-with-watson-xxx/terraform/.kube/4c9ce77bccb836b63d751f6689a58b046cb7089b6f40c2aa91a881cc716b584c_niklas-cluster_k8sconfig/config.yml
│ WARNING: Kubernetes configuration file is world-readable. This is insecure. Location:
│ /terraform/cluster-with-watson-xxx/terraform/.kube/4c9ce77bccb836b63d751f6689a58b046cb7089b6f40c2aa91a881cc716b584c_niklas-cluster_k8sconfig/config.yml
│ ---
│ # Source: argocd/charts/openshift-gitops/templates/subscription.yaml
│ apiVersion: operators.coreos.com/v1alpha1
│ kind: Subscription
│ metadata:
│   name: openshift-gitops-operator
│   namespace: openshift-operators
│   labels:
│     helm.sh/chart: openshift-gitops-0.9.1
│     app.kubernetes.io/name: openshift-gitops-operator
│     app.kubernetes.io/instance: argocd
│     app.kubernetes.io/version: "0.4.0"
│     app.kubernetes.io/managed-by: Helm
│ spec:
│   channel: stable
│   installPlanApproval: Automatic
│   name: openshift-gitops-operator
│   source: redhat-operators
│   sourceNamespace: openshift-marketplace
│   config:
│     env:
│       - name: DISABLE_DEX
│         value: "false"
│ WARNING: Kubernetes configuration file is group-readable. This is insecure. Location:
│ /terraform/cluster-with-watson-xxx/terraform/.kube/4c9ce77bccb836b63d751f6689a58b046cb7089b6f40c2aa91a881cc716b584c_niklas-cluster_k8sconfig/config.yml
│ WARNING: Kubernetes configuration file is world-readable. This is insecure. Location:
│ /terraform/cluster-with-watson-xxx/terraform/.kube/4c9ce77bccb836b63d751f6689a58b046cb7089b6f40c2aa91a881cc716b584c_niklas-cluster_k8sconfig/config.yml
│ Error: query: failed to query with labels: secrets is forbidden: User "IAM#xxx@de.ibm.com" cannot list resource "secrets" in API group "" in
│ the namespace "openshift-operators"
│ 
╵
╷
│ Error: local-exec provisioner error
│ 
│   with module.argocd-bootstrap.module.openshift_cicd.null_resource.namespaces,
│   on .terraform/modules/argocd-bootstrap.openshift_cicd/main.tf line 30, in resource "null_resource" "namespaces":
│   30:   provisioner "local-exec" {
│ 
│ Error running command '.terraform/modules/argocd-bootstrap.openshift_cicd/scripts/create-namespaces.sh '["sealed-secrets"]'': exit status 1. Output:
│ Creating namespace: sealed-secrets
│ Error from server (Forbidden): namespaces is forbidden: User "IAM#nxxxxff@de.ibm.com" cannot create resource "namespaces" in API group "" at the
│ cluster scope
│ 
╵

**Comment by nheidloff** [comment]
related to https://github.com/cloud-native-toolkit/iascable/issues/235

The third attempt worked

**Comment by triceam** [comment]
@seansund any ideas here?   I've not seen this one before.  Seems a bit odd b/c its related to ibm cloud user account permission.   

@nheidloff you're an admin on the cluster, right?   
Also, what region is this cluster in?

**Comment by seansund** [comment]
I also think we should open an issue against the IBM Cloud terraform provider and IBM Cloud. We already wait for "IngressReady" on the cluster resource before we proceed. Creating the ingress takes a LONG time compared to setting up the masters ("MasterNodeReady") or provisioning the workers ("OneWorkerNodeReady"). There is no reason the IAM sync process can't start as soon as the master node is ready and therefore no reason the IAM sync shouldn't have completed by the time the ingress is ready. At the very least I think the "IngressReady" check should also include an IAM ready check. If not there should be a 4th "wait_till" value of "IAMReady" to check for that. Here's the [terraform provider resource](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/container_vpc_cluster#wait_till) for reference
