### ISSUE TITLE
iascable build gives confusing error when not specifying input file

### ISSUE THREAD

**Issue by andrewferrier** [cloud-native-toolkit/iascable#87]
I cloned `isacable`, ran `npm install`, then `./iascable build`. I was expecting either it would default to `bom.yaml` (I'd copied in one from [here](https://github.ibm.com/gsi-labs/ibmcloud-reference-architectures/blob/main/000-account-setup/bom.yaml)), or give me an error, but I saw this:

```
Name: component
Loading catalog from url: https://modules.cloudnativetoolkit.dev/index.yaml
? Which ai-ml module(s) should be used?
❯◯ gitops-cp-bas: Module to populate a gitops repo with the resources to provision cp-bas
```

I'm definitely not doing ai-ml or cp-bas ;) Not sure what this is defaulting to but this doesn't seem quite right?

**Comment by seansund** [comment]
If you don't provide a BOM file either with `-i` or `-r` the cli will prompt you with options from the catalog to build the BOM. This is an old behavior from when we first created the CLI and hadn't fully built out the BOM definition. This functionality isn't really appropriate anymore so we can remove it.
